server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

spring:
  jpa:
    show-sql: true
  messages:
    basename: messages
  security:
    user:
      name: username
      password: passw0rd
  mail:
    host: smtp.naver.com
    port: 587
    username: n_nv711@naver.com
    password: 
  mvc: 
    view:
      suffix: .html
management:
  endpoints:
    web:
      exposure:
        include: "*"
